version: '3.7'

services:
  traefik:
    image: torinasakura/traefik:epochcrysis
    command: --api --docker
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      default:
      traefik:
        ipv4_address: 172.16.233.66

  yarn:
    image: node:alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - modules:/workspace/node_modules
      - yarncache:/workspace/.yarn-cache
    environment:
      - YARN_CACHE_FOLDER=/workspace/.yarn-cache
    entrypoint: yarn

  wordpress-db:
    image: mariadb
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_DATABASE=wordpress
      - MYSQL_PASSWORD=password
      - MYSQL_USER=wordpress

  wordpress-fpm:
    build: ./config/wordpress
    command: bash -c 'install_wordpress && docker-entrypoint.sh php-fpm'
    user: www-data
    environment:
      WORDPRESS_ADMIN_USER: admin
      WORDPRESS_ADMIN_PASSWORD: password
      WORDPRESS_ADMIN_EMAIL: me@epochcrysis.band
      WORDPRESS_DB_HOST: wordpress-db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_PASSWORD: password
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_TITLE: Project Starter
      WORDPRESS_URL: https://wp.local.epochcrysis.band
      WORDPRESS_PREVIEW_URL: https://local.epochcrysis.band
      #CURLOPT_SSL_VERIFYPEER: 0
    volumes:
      - wordpress:/var/www/html
    depends_on:
      - traefik
      - wordpress-db
    networks:
      - default
      - traefik

  wordpress:
    image: nginx
    volumes:
      - wordpress:/var/www/html
      - ./config/wordpress/nginx.conf:/etc/nginx/conf.d/default.conf
    labels:
      - 'traefik.frontend.rule=Host:wp.local.epochcrysis.band'
      - 'traefik.protocol=http'
      - 'traefik.port=80'
    depends_on:
      - traefik
      - wordpress-fpm
    networks:
      - default
      - traefik

  site:
    image: node:alpine
    working_dir: /workspace
    volumes:
      - ./:/workspace
      - modules:/workspace/node_modules
    entrypoint: yarn site:dev
    environment:
      NODE_TLS_REJECT_UNAUTHORIZED: 0
    labels:
      - 'traefik.frontend.rule=Host:local.epochcrysis.band'
      - 'traefik.protocol=http'
      - 'traefik.port=3000'
    depends_on:
      - traefik
      - wordpress
    networks:
      - default
      - traefik
    extra_hosts:
      - 'wp.local.epochcrysis.band:172.16.233.66'

volumes:
  modules:
  yarncache:
  wordpress:

networks:
  traefik:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.16.233.0/24
